# Generated by Django 3.1.5 on 2021-07-27 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(max_length=100, verbose_name='full name')),
                ('father_name', models.CharField(max_length=100, verbose_name='father name')),
                ('mobile_number', models.CharField(max_length=20, unique=True, verbose_name='mobile number')),
                ('cnic', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='id card number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'surveyor'), (3, 'grower')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_otp', models.IntegerField(default=3131, verbose_name='activation otp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name_address', models.CharField(blank=True, max_length=250, null=True)),
                ('surveyor_address', models.CharField(blank=True, max_length=250, null=True)),
                ('family_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passbook_number', models.CharField(blank=True, max_length=50, null=True)),
                ('circle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('village_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name_address', models.CharField(blank=True, max_length=250, null=True)),
                ('grower_address', models.CharField(blank=True, max_length=250, null=True)),
                ('own_land_area', models.IntegerField(blank=True, null=True)),
                ('lease_land_area', models.IntegerField(blank=True, null=True)),
                ('total_land', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_address', models.CharField(blank=True, max_length=250, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
