# Generated by Django 3.2.5 on 2021-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_activation_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindetails',
            old_name='area_name',
            new_name='administration_area',
        ),
        migrations.AddField(
            model_name='admindetails',
            name='bank_name_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activation_otp',
            field=models.IntegerField(default=8014, verbose_name='activation otp'),
        ),
    ]
