# Generated by Django 3.2.5 on 2021-07-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210729_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_otp',
            field=models.IntegerField(default=6777, verbose_name='activation otp'),
        ),
    ]
