# Generated by Django 3.2.5 on 2021-08-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_activation_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
