# Generated by Django 3.2.5 on 2021-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_notification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyordetails',
            name='family_number',
        ),
        migrations.RemoveField(
            model_name='surveyordetails',
            name='passbook_number',
        ),
        migrations.AddField(
            model_name='growerdetails',
            name='family_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='growerdetails',
            name='passbook_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
