# Generated by Django 3.2.5 on 2021-07-25 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('message', models.TextField(blank=True, null=True, verbose_name='body')),
                ('seen_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='timestamp')),
                ('deleted_by_user', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='timestamp')),
                ('deleted_by_recipient', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='timestamp')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageAttachmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.PositiveSmallIntegerField(choices=[(1, 'text'), (2, 'doc'), (3, 'image'), (4, 'audio'), (5, 'video')])),
                ('attachment_file', models.FileField(upload_to='message_attachments')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_id', to='chat.messagemodel')),
            ],
            options={
                'verbose_name': 'message_attachment',
                'verbose_name_plural': 'message_attachments',
            },
        ),
    ]
