# Generated by Django 3.2.5 on 2021-07-27 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowerFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variety', models.PositiveSmallIntegerField(choices=[(1, 'sugarcane')])),
                ('area_auto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_manual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plantation_date', models.DateField()),
                ('plantation_type', models.PositiveSmallIntegerField(choices=[(1, 'ratoon'), (2, 'planted')])),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('surveyed_at', models.DateTimeField(blank=True, null=True)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grower_id', to=settings.AUTH_USER_MODEL)),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCoordsBySurveyorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=100)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=100)),
                ('coords_seq', models.IntegerField()),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_coords_by_surveyor', to='growerfields.growerfieldmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCoordsByGrowerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('coords_seq', models.IntegerField()),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_coords_by_grower', to='growerfields.growerfieldmodel')),
            ],
        ),
    ]
