# Generated by Django 3.2.5 on 2021-07-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growerfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=100, null=True),
        ),
    ]
