# Generated by Django 3.2.5 on 2021-07-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growerfields', '0002_auto_20210728_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=1.0, max_digits=100),
            preserve_default=False,
        ),
    ]
