# Generated by Django 3.2.5 on 2021-07-28 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growerfields', '0003_auto_20210728_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcoordsbygrowermodel',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_coords', to='growerfields.growerfieldmodel'),
        ),
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_coords', to='growerfields.growerfieldmodel'),
        ),
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
