# Generated by Django 3.2.5 on 2021-07-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growerfields', '0005_auto_20210730_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcoordsbygrowermodel',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fieldcoordsbygrowermodel',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fieldcoordsbysurveyormodel',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='growerfieldmodel',
            name='area_auto',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='growerfieldmodel',
            name='area_manual',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
