# Generated by Django 3.2.5 on 2021-08-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growerfields', '0008_auto_20210805_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropVarietyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variety', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CropVarietySubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variety_sub_type', models.CharField(max_length=50)),
                ('crop_variety_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_type', to='growerfields.cropvarietytype')),
            ],
        ),
        migrations.AlterField(
            model_name='growerfieldmodel',
            name='crop_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_variety_type', to='growerfields.cropvarietytype'),
        ),
    ]
