# Generated by Django 3.2.5 on 2021-08-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growerfields', '0009_auto_20210806_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropvarietysubtype',
            old_name='crop_variety_type_id',
            new_name='crop_variety_type',
        ),
    ]
