# Generated by Django 3.2.5 on 2021-08-06 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growerfields', '0011_alter_cropvarietysubtype_crop_variety_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='growerfieldmodel',
            name='crop_variety_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_variety_subtype', to='growerfields.cropvarietysubtype'),
        ),
    ]
